name: Cypress Tests with Dependency and Artifact Caching

on: push  # Run this workflow whenever a push occurs

jobs:
  install:  # Job to install dependencies and build the project
    runs-on: ubuntu-24.04  # Specifies the runner OS

    steps:
      - name: Checkout  # Clone the repository onto the runner
        uses: actions/checkout@v4

      - name: Cypress install  # Install Cypress and project dependencies
        uses: cypress-io/github-action@v6
        with:
          runTests: false  # Prevents Cypress from running tests during installation
          build: npm run build  # Builds the project before running tests

      - name: Save build folder  # Uploads the build folder as an artifact for later jobs
        uses: actions/upload-artifact@v4
        with:
          name: build  # Artifact name
          if-no-files-found: error  # Fail if the build folder is missing
          path: build  # Path to the folder that needs to be saved

  cypress-run:  # Job to run Cypress tests
    runs-on: ubuntu-24.04  # Specifies the runner OS
    needs: install  # Ensures this job runs only after the install job completes

    strategy:
      fail-fast: false  # If one test fails, others continue running
      matrix:
        containers: [1, 2, 3, 4, 5]  # Runs tests in parallel across multiple containers

    steps:
      - name: Checkout  # Clone the repository onto the runner
        uses: actions/checkout@v4

      - name: Download the build folder  # Retrieve the build artifact from the install job
        uses: actions/download-artifact@v4
        with:
          name: build  # Specifies the artifact name to download
          path: build  # Destination path to store the downloaded files

      - name: Install dependencies  # Ensure dependencies are installed before running tests
        run: npm install

      - name: Cypress run  # Execute Cypress tests
        uses: cypress-io/github-action@v6
        with:
          start: npm start  # Starts the application before running tests
          browser: chrome  # Runs tests using Chrome browser
          wait-on: http://localhost:3000  # Waits for the application to be available before running tests
          record: true  # (Optional) If using Cypress Dashboard for test recording
        env:
          CYPRESS_BASE_URL: ${{ secrets.CYPRESS_BASE_URL }}  # Pass environment variables if required

      - name: Upload Cypress test results  # Save Cypress test reports as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cypress-results
          path: cypress/results
          if-no-files-found: ignore  # Avoid errors if no reports exist
